name: CI

on:
  push:
    branches: [ 'main', 'ci' ]
  pull_request:
    branches: [ 'main' ]

env:
  CI: true

permissions: {}

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os:
          - macos-latest
          - ubuntu-24.04
          - windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --no-fund
      - name: Use Rust 1.84
        uses: dtolnay/rust-toolchain@1.84
      - run: npm run build
      - run: npm test

  eslint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Use Node.js 22
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22
      - run: npm install --no-audit --ignore-scripts --no-fund
      - run: npm run lint

  rustfmt:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Use Rust 1.84
        uses: dtolnay/rust-toolchain@1.84
      - run: cargo fmt -- --check
